fix input

diff --git a/actions/tests/case/action.yml b/actions/tests/case/action.yml
--- a/actions/tests/case/action.yml
+++ b/actions/tests/case/action.yml
@@ -15,15 +15,17 @@ runs:
     - name: Check pages file name case
       shell: sh
       run: |
-        if
-          find $DOC_DIR -name "*.md" | ( ! grep -P -v "^[[:lower:][:digit:]\/\-_]+\.md$" )
-        then
-          echo "::notice ::No file paths casing issue in $DOC_DIR."
-          exit 0;
-        else
-          echo "::error ::Some file paths are not lowercase in $DOC_DIR."
-          echo "::notice ::Accepted characters: lowercase letters, digits, . (dot) - (dash) and _ (underscore)"
-          echo "::notice ::Correct example: my-folder/my-file-name_new2.md"
-          echo "::notice ::Wrong example: My-Folder/MyFile-NAME.old.md"
-          exit 1;
+        echo "Testing file case in ${{ inputs.DOC_DIR }}."
+        passed=true
+        for filename in `find ${{ inputs.DOC_DIR }} -name "*.md" | ( ! grep -P -v "^[[:lower:][:digit:]\/\-_]+\.md$" )`
+        do
+          echo "$filename"
+          echo "::error file=$filename ::File path must be only lowercase letters, digits, - (dash) and _ (underscore)"
+          passed=false
+        done;
+        if [ "$passed" = false ] ; then
+          echo "::error ::Some files path are incorrect. Check error annotations in the pull request."
+          echo "Correct example: my-folder/my-file-name_new2.md"
+          echo "Wrong example: My-Folder/MyFile-NAME.old.md"
+          exit 1
         fi
